### ISSUE TITLE
Found two issues in 3.03 

### ISSUE THREAD

**Issue by yinx2002** [Pruszko/DispersionReticle#17] opened 2024-01-22 07:24 UTC
1.  In WOT ladder mode , if "use server aim" is on in client and both "server reticle" and "server reticle extend" is off in mod, after you change vehicle during count down , the reticle will disappear when count down finish.

Not changing vehicle will not lead to this , and in standard mode , this problem also exist:  although you can not change vehicle during count down , the server reticle and server reticle extend will disappear , only  server rectile of the client is there.

Although

2.   In standard mode  , if you enter the game with "server aim": off ,    "server reticle": on,   it will be normal until you lock enemy using right mouse button, after that the reticle will disappear , and reappear after you right click again( dismiss the lock)

**Comment by yinx2002** [comment] 2024-01-23 02:37
> 1. By WoT ladder mode, you mean Onslaught?
>    Reticles should be invisible during battle countdown. Could you provide tank names and `config.json` on which you saw them during countdown (I guess with `Use server aim` in game settings)?
>    I didn't manage to reproduce that


Yes， onSlaught. The steps to reproduce are these:
a.   select `Use server aim`   , and also select one of "server reticle" or "server reticle extended" in mod
b.   enter onSlaught mode 
c.   change vehicle during count down ( reticle is invisible during that time , it's normal)
d.   After count down finish , reticle has not shown up.

the step C is a must , will not reproduce without it.

 
> 2. It is intended behavior (unfortunately)
>    When game does auto-aiming, it changes "aiming state" to client-side-only aiming and game engine stops providing server reticle data to game (and my mod relies on it's callbacks)
>    If I don't hide them, it would be displayed "frozen" anyway (I confirmed that some longer time ago)


I just check in safe-mode client ( without any mod). I select `Use server aim` in game , and enter battle , after locking target , the reticle displayed as normal. So this is not a mechanism or restriction in game itself ?

**Comment by Pruszko** [comment] 2024-01-23 17:55
1\. When I tried to reproduce that, I'm using:
* checked `Use server aim`
* enabled `server-reticle` (other functions turned off)
* I switched tank from STB-1 to Obj. 277 during battle countdown

The only reticle that is displayed is normal green server reticle as on screen 
![obraz](https://github.com/Pruszko/DispersionReticle/assets/76662097/f476d12a-1387-48f8-a450-4f255fbed5a6)

Behavior on screen is normal, because `Use server aim` in game settings is checked, which basically enables standard non-modded builtin server aiming.  

Can you provide screenshot of what you've got on screen after those steps?

2\. Non-modded game does a little trick with this.

Builtin client reticle and server reticle is one and the same reticle (it's like 2 in 1) - only "source of updates" changes.  
That's why, even when server aiming is temporarily turned off during auto-aiming, reticle looks the same.

I can attempt to do similarly (ie. make `server-reticle` behave like client-side one during auto-aiming), but keep in mind that server reticles would then exactly overlap with normal reticles during auto-aiming.  

I'm not 100% sure if it is desirable for users

**Comment by yinx2002** [comment] 2024-01-25 07:04
First problem reproduced in  3.04 .

enabled `Use Server Aim`

My setting :(temporily renamed the CN translation file to get English screenshot)

![image](https://github.com/Pruszko/DispersionReticle/assets/66009650/843993d0-58bf-48b2-a350-44b2914ab9d7)

Enter onslaught battle with  110E3

![image](https://github.com/Pruszko/DispersionReticle/assets/66009650/abd70c09-f533-4f11-9f52-dc84294b528f)

change to Minotauro
![image](https://github.com/Pruszko/DispersionReticle/assets/66009650/5b03d628-2018-4bfa-8f0a-58b71af309a0)

After count down,  reticle disapear: 

![c2dfdeedebdeb278665e18661e59056](https://github.com/Pruszko/DispersionReticle/assets/66009650/9270c51b-7f55-4d60-97d1-416e43a9d976)
![4245a2939dc387cc2ba844f48a5778f](https://github.com/Pruszko/DispersionReticle/assets/66009650/7fea6cf7-a359-4b7a-88cf-dae82c87a385)

**Comment by yinx2002** [comment] 2024-01-25 07:10
deselect the `Use Server Aim` , the reticle will be back . But only the in-game server reticle is displayed . ( When you only select server reticle extended option and set a different color, it can be seen more clearly)

**Comment by yinx2002** [comment] 2024-01-25 07:13
here is python.log [pythonlog.txt](https://github.com/Pruszko/DispersionReticle/files/14047961/pythonlog.txt), there are lots of gunmarker errors in it , maybe they are the clue.

**Comment by Pruszko** [comment] 2024-01-25 14:21
I think I found the issue by logs, Kurzdor pointed it out for me as well

Will post update in very near future

**Comment by yinx2002** [comment] 2024-01-25 14:51
Actually in standard mode , this problem also exist. The "server reticle" or "server reticle extended" will be replaced by in-game one. But because we can not change vehicle in that mode , so the reticle will not disappear , so it is not very apparently.

And maybe this behavior is acceptable.

**Comment by Pruszko** [comment] 2024-01-25 15:10
That bug is most likely caused due to my mistake of not accounting ASIA/CN clients in few code overrides

Check that version, it should work as I initially expected in above comments:
[DispersionReticle_3.0.5.zip](https://github.com/Pruszko/DispersionReticle/files/14053822/DispersionReticle_3.0.5.zip)

**Comment by yinx2002** [comment] 2024-01-25 15:31
Just tested in standard mode ,  all seems fine. ( 3.04 also make reticle disappear even in standard mode ).    Has no time to check in onSlaught today.

Attached pythonlog

[pythonlog.txt](https://github.com/Pruszko/DispersionReticle/files/14054071/pythonlog.txt)

**Comment by Pruszko** [comment] 2024-01-25 16:09
Everything seems fine, I'll release 3.0.5 with those changes

Thanks for logs and checking things out :)

**Comment by Pruszko** [comment] 2024-01-26 18:01
I'll close this ticket, I hope all issues have been resolved for you

If you still have any suggestions or issues, feel free to make new ticket :)

**Closed by Pruszko** 2024-01-26 18:01 UTC
